# If true, allow intake non-FHIR fixture (local only).
nonfhir_fixture: true

# If true, use FHIR logger. Log file will be exported to STDOUT.
verbose: false

# Endpoint against which TestScripts will be executed.
server_url: https://server.fire.ly

# Relative path to the directory containing the TestScript resources (as JSON or XML) to be executed by the engine
testscript_path: ./TestScripts
 
# Name of TestScript under TESTSCRIPT_PATH to be executed
# Name should match Testscript.name
# If empty, all files under TESTSCRIPT_PATH will be executed
# Handling multiple TestScript names is to be added
testscript_name: testscript-example-general

# Dynamic variables replace defaultValue in variable in TestScript
# This will uniformly apply to all runnables. For example, if two TestScripts have same variable name, this will apply to both.
# Syntax: name=value (no space before and after =)
variable:
- name1=value1
- name2=value2

# The relative to the directory containing the TestReports output following their partner TestScript execution
# Files containing TestReport instances will be placed in a subfolder corresponding to the execution completion time
testreport_path: "TestReports"

# If specified, a summary report csv file named execution_summary_[timestamp].csv will be created within the specified relative folder
# The file will include the id, name, and title of each TestScript executed along with the overall pass/fail result and the file containing the TestReport with details
summary_path: "TestReports"

# If specified, use the external validator with URL
# If not, use the internal validator based on Ruby Crucible validator: https://github.com/fhir-crucible/fhir_models#validation
ext_validator: https://inferno.healthit.gov/validatorapi

# If specified, use the external FHIR Path evaluator with URL
# If not, use the internal evaluator based on Ruby Crucible FHIR path evaluator: https://github.com/fhir-crucible/fhir_models
ext_fhirpath: https://inferno.healthit.gov/validatorapi

# List of locations holding profile StructureDefinitions to be used for profile validation
# May be a web url, a relative file, or a relative directory (profiles in sub-directories not included)
# StructureDefinitions loaded from this configuration setting take precedence over StructureDefinitions 
# accessed from canonical URLs in TestScripts that resolve to StructureDefinitions. 
# This allows for validation against unpublished versions of profiles.
profile: 
- Profiles