# If true, allow intake non-FHIR fixture (local only).
nonfhir_fixture: false

# If true, use FHIR logger. Log file will be exported to STDOUT.
verbose: false

# Endpoint against which TestScripts will be executed.
server_url: https://server.fire.ly

# Relative path to the directory containing the TestScript resources (as JSON or XML) to be executed by the engine
testscript_path: /spec/examples
 
# Name of TestScript under TESTSCRIPT_PATH to be executed
# Name should match Testscript.name
# If empty, all files under TESTSCRIPT_PATH will be executed
# Handling multiple TestScript names is to be added
# testscript_name: UsMcodeIdentifyCancerPatientsByGroup
testscript_name: UsMcodeProfileSearchComorbidities

# Dynamic variables replace defaultValue in variable in TestScript
# This will uniformly apply to all runnables. For example, if two TestScripts have same variable name, this will apply to both.
# Syntax: name=value (no space before and after =)
variable:

# The relative to the directory containing the TestReports output following their partner TestScript execution
testreport_path: "./TestReports"

# If specified, a summary report csv file named execution_summary_[UTC timestamp].csv will be created within the specified relative folder
# The file will include the id, name, and title of each TestScript executed and the overall pass/fail result
summary_path:

# If specified, use the external validator with URL
# If not, use the internal validator based on Ruby Crucible validator: https://github.com/fhir-crucible/fhir_models#validation
ext_validator:
# https://inferno.healthit.gov/validatorapi

# If specified, use the external FHIR Path evaluator with URL
# If not, use the internal evaluator based on Ruby Crucible FHIR path evaluator: https://github.com/fhir-crucible/fhir_models
ext_fhirpath:
# https://inferno.healthit.gov/validatorapi